# Generated by Django 2.2.5 on 2019-10-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20191028_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
