# Generated by Django 2.2.5 on 2019-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20191028_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='duracion',
            field=models.CharField(choices=[('1MIN', '1 Minutos'), ('5MIN', '5 Minutos'), ('1HR', '1 Hora')], default='5MIN', max_length=10),
        ),
    ]
