# Generated by Django 2.2.5 on 2019-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_confurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
