# Generated by Django 2.2.5 on 2019-11-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0006_auto_20191106_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='conf_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='url.ConfUrl'),
        ),
    ]
